#!/usr/bin/env node
/**
 * LombokPDF — SBOM Generator
 * Generates SPDX 2.3 Software Bill of Materials for each release.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { createHash } from 'node:crypto'

const pkg      = JSON.parse(readFileSync('package.json', 'utf-8'))
const lockfile = existsSync('package-lock.json')
  ? JSON.parse(readFileSync('package-lock.json', 'utf-8'))
  : { packages: {} }

const now = new Date().toISOString()

// Collect all packages
const packages = []

for (const [pkgPath, meta] of Object.entries(lockfile.packages ?? {})) {
  if (pkgPath === '') continue // root
  if (meta.dev) continue       // exclude devDeps from SBOM

  const name    = pkgPath.replace('node_modules/', '')
  const version = meta.version ?? 'unknown'
  const license = meta.license ?? 'UNKNOWN'
  const integrity = meta.integrity ?? ''

  // Generate SPDX ID
  const spdxId  = `SPDXRef-Package-${name.replace(/[^a-zA-Z0-9.-]/g, '-')}-${version}`

  packages.push({
    SPDXID:            spdxId,
    name,
    versionInfo:       version,
    downloadLocation:  `https://registry.npmjs.org/${name}/-/${name}-${version}.tgz`,
    filesAnalyzed:     false,
    licenseConcluded:  license,
    licenseDeclared:   license,
    copyrightText:     'NOASSERTION',
    checksum:          integrity ? { algorithm: 'SHA512', checksumValue: integrity.replace('sha512-', '') } : undefined,
  })
}

// Build SPDX 2.3 document
const sbom = {
  spdxVersion:    'SPDX-2.3',
  dataLicense:    'CC0-1.0',
  SPDXID:         'SPDXRef-DOCUMENT',
  name:           `${pkg.name}-${pkg.version}`,
  documentNamespace: `https://lombokpdf.dev/sbom/${pkg.name}/${pkg.version}/${Date.now()}`,
  creationInfo: {
    created:  now,
    creators: ['Tool: LombokPDF-AuditSBOM-1.0.0', `Organization: ${pkg.author ?? 'Lombok Digital'}`],
    comment:  'Generated by LombokPDF audit:sbom script',
  },
  packages: [
    // Root package
    {
      SPDXID:           'SPDXRef-Package-root',
      name:             pkg.name,
      versionInfo:      pkg.version,
      downloadLocation: pkg.repository?.url ?? 'https://github.com/codinglombok/lombokpdf',
      filesAnalyzed:    false,
      licenseConcluded: pkg.license,
      licenseDeclared:  pkg.license,
      copyrightText:    `Copyright 2026 Lombok Digital`,
      supplier:         `Organization: Lombok Digital`,
      primaryPackagePurpose: 'LIBRARY',
    },
    ...packages,
  ],
  relationships: [
    {
      spdxElementId:      'SPDXRef-DOCUMENT',
      relationshipType:   'DESCRIBES',
      relatedSpdxElement: 'SPDXRef-Package-root',
    },
    ...packages.map(p => ({
      spdxElementId:      'SPDXRef-Package-root',
      relationshipType:   'DEPENDS_ON',
      relatedSpdxElement: p.SPDXID,
    })),
  ],
}

// Write SBOM files
const sbomJSON = JSON.stringify(sbom, null, 2)
writeFileSync('sbom.spdx.json', sbomJSON)

// Also write human-readable summary
const summary = [
  `# LombokPDF SBOM Summary`,
  `Generated: ${now}`,
  `Package: ${pkg.name}@${pkg.version}`,
  `License: ${pkg.license}`,
  `Dependencies: ${packages.length}`,
  ``,
  `## Runtime Dependencies`,
  ...packages.map(p => `- ${p.name}@${p.versionInfo} (${p.licenseConcluded})`),
].join('\n')

writeFileSync('sbom-summary.md', summary)

// Hash the SBOM for verification
const hash = createHash('sha256').update(sbomJSON).digest('hex')
writeFileSync('sbom.spdx.json.sha256', hash)

console.log(`\x1b[32m✓ SBOM generated:\x1b[0m`)
console.log(`  sbom.spdx.json      (SPDX 2.3 JSON, ${packages.length} packages)`)
console.log(`  sbom.spdx.json.sha256`)
console.log(`  sbom-summary.md`)
console.log(`  SHA-256: ${hash}`)
